lamon/views/game.py
from flask import Blueprint, render_template, request, current_app, abort, flash, redirect, url_for
from flask_user import roles_required
from sqlalchemy.orm.exc import NoResultFound
from sqlalchemy.exc import IntegrityError

from ..models import Game, Watcher, User, Nickname
from .. import db


game_blueprint = Blueprint('games', __name__, template_folder='templates')


@game_blueprint.route('/')
def index():
    games = Game.query.all()
    return render_template('game/index.html', games=list(games))


@game_blueprint.route('/<int:game_id>/')
def index_one(game_id):
    try:
        game = Game.query.filter(Game.id == game_id).one()
    except NoResultFound:
        abort(404)

    watchers = Watcher.query.filter(Watcher.game == game).all()
    players = User.query.filter(User.nicknames.any(Nickname.game == game)).all()
    for player in players: # XXX Don't use this
        setattr(player, 'nickname',
                Nickname.query.\
                    filter(Nickname.user == player, Nickname.game == game)\
                    .one().nick)

    return render_template('game/index_one.html', game=game, watchers=watchers,
                           players=players)

lamon/views/user.py
from flask import Blueprint, render_template
from flask_user import login_required
from sqlalchemy.orm.exc import NoResultFound

from ..models import User, Nickname

user_blueprint = Blueprint('users', __name__, template_folder='templates')

@user_blueprint.route('/')
def index():
    users = User.query.all()
    return render_template('user/index.html', users=list(users))

@user_blueprint.route('/<int:user_id>')
def index_one(user_id):
    try:
        user = User.query.filter(User.id == user_id).one()
    except NoResultFound:
        abort(404)

    nicknames = Nickname.query.filter(Nickname.user == user).all()
    return render_template('user/index_one.html', user=user, nicknames=nicknames)

lamon/templates/user/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Users</h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Username</th>
                <th scope="col">Score</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>
                        {{ user.username }}
                        <a href="{{ url_for('users.index_one', user_id = user.id) }}">
                            (Profile)
                        </a>
                    </td>
                    <td>{{ stats_score(user_id=user.id) }}</td>
            {% endfor %}
{% endblock %}

lamon/templates/user/index_one.html
{% extends "base.html" %}

{% block title %}{{ user.username }}'s Profile{% endblock %}

{% block content %}
    <h1> {{ user.username }}'s Profile:</h1>

    <div id="score-plot"></div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">Game</th>
                <th scope="col">Nickname</th>
                <th scope="col">Score</th>
            </tr>
        </thead>
        <tbody>
            {% for nick in nicknames %}
            <tr>
                <td>
                    <a href="{{ url_for('games.index_one', game_id=nick.game.id) }}">
                        {{ nick.game.name }}
                    </a>
                </td>
                <td>{{ nick.nick }}</td>
                <td>{{ stats_score(game_id=nick.game.id, user_id=user.id) }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </thead>
{% endblock %}

{% block scripts %}
    <script src="https://cdn.plot.ly/plotly-1.2.0.min.js"></script>
    <script>
        var data = [];
        var plot = {};

        {% for nick in nicknames %}
            plot = {
                {% set s = stats_score(game_id=nick.game.id, user_id=user.id, timeline=True) %}
                {% set x = s[0] %}
                {% set y = s[1] %}
                type: "scatter",
                mode: "lines",
                name: "{{ nick.game.name }}",
                x: {{ x|tojson }},
                y: {{ y|tojson }}
            }

            data.push(plot);
        {% endfor %}

        plot = {
            {% set s = stats_score(user_id=user.id, timeline=True) %}
            {% set x = s[0] %}
            {% set y = s[1] %}
            type: "scatter",
            mode: "lines",
            name: "complete",
            x: {{ x|tojson }},
            y: {{ y|tojson }}
        }

        data.push(plot);

        var layout = {
            title: "{{ user.username }}'s Scores"
        };

        Plotly.newPlot('score-plot', data, layout);
    </script>
{% endblock %}